### ISSUE TITLE
sap_preconfigure_db_group_name does not correctly set the database group name

### ISSUE THREAD

**Issue by michaelk71** [linux-system-roles/sap-preconfigure#141]
Dear developers, 

in my opinion, the variable [**sap_preconfigure_db_group_name**](https://github.com/linux-system-roles/sap-preconfigure#linux-group-name-of-the-database-user) does not correctly set the database group name in ```/etc/security/limits.d/99-sap.conf``` as suggested in [SAP note 2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration](https://launchpad.support.sap.com/#/notes/2772999/E) and [RHEL: How to set ulimit values](https://access.redhat.com/solutions/61334)  or `man limits.conf`.
The database group name should be preceded by an '@' sign, e.g. ```@dba``` for HANA or ```@sdba``` for MaxDB databases.

I think, in the same context of this configuration, it could be useful to introduce an additional variable, e.g.  ```sap_preconfigure_sapsys_group_name``` which could set the Linux group which is used for the SAP instance (e.g. ```@sapsys```), 
so that in the end ```/etc/security/limits.d/99-sap.conf``` looks like this:
```
# number of open files per process
@sapsys hard    nofile  65536
@sapsys soft    nofile  65536
@sdba hard nofile 65536
@sdba soft nofile 65536

# number of processes per user
@sapsys hard nproc unlimited
@sapsys soft nproc unlimited
@sdba hard nproc unlimited
@sdba soft nproc unlimited
```

I am using ansible-2.9.21-1.el8ae.noarch on RHEL 8.4

Best regards
Michael

Just for reference:
> [2772999 - Red Hat Enterprise Linux 8.x: Installation and Configuration](https://launchpad.support.sap.com/#/notes/2772999/E), Version 16 of 17 May 2021
> 
> [...]
> ## Configuring Process Resource Limits
> 
> ### Number of open files per process 
> 
> Some components (e.g. the SAP J2EE engine, Oracle RDBMS software, ...) need to keep a large number of file handles opened simultaneously. The RHEL 8 default is 1024, which is too small in certain cases. To increase the limit of files one process can open at a time for all OS users of the SAP system and DB, please create the file /etc/security/limits.d/99-sap.conf with the following content (these are the recommended minimum values, higher values can be used too):
> ```
> @<group>    hard    nofile    65536
> @<group>    soft    nofile    65536
> ```
> where <group> is the name of the RHEL group which is used for the SAP instance and of the RHEL group which is used for the database processes. Example:
> ```
> @sapsys    hard    nofile    65536
> @sapsys    soft     nofile    65536
> @dba       hard    nofile    65536
> @dba       soft     nofile    65536
> ```
> These settings only become effective for new processes, so you have to logout and login all users belonging to these groups and to restart all processes running under those users.
> 
>### Number of processes per user
> 
> Some components need to create a higher amount of processes per user from time to time, which might exceed the default maximum allowed number of processes per user on RHEL 8. In order to avoid this, please make sure that file /etc/security/limits.d/99-sap.conf has entries like the following:
> ```
> @<group>    hard    nproc    unlimited
> @<group>    soft    nproc    unlimited
> ```
> where <group> is the name of the RHEL group which is used for the SAP instance and of the RHEL group which is used for the database processes. Example:
> ```
> @sapsys    hard    nproc    unlimited
> @sapsys    soft    nproc    unlimited
> @dba       hard    nproc    unlimited
> @dba       soft    nproc    unlimited
> ```
> [...]

**Comment by berndfinger** [comment]
Thanks for reporting this. It looks like it is documented in https://github.com/linux-system-roles/sap-preconfigure/issues/81 and fixed in a more recent version of role sap-preconfigure. Can you please check?

**Comment by michaelk71** [comment]
Hello Bernd, 

thank you for your fast response. 
Issue #81 is indeed referencing to the same issue. 

sap_preconfigure delivered by RHEL 8.4 as part of the latest rhel-system-roles-sap-1.1.1-1.el8_1.noarch, does not have the patch included. 

I am still new to Ansible and trying to find a reproducable way to properly update the sap_preconfigure role. 
`ansible-galaxy install berndfinger.sap_preconfigure`
tells me that 
`berndfinger.sap_preconfigure was not found on https://galaxy.ansible.com/api/`

(But that's another story ;-) )

Thanks for the great work.

Best regards
Michael

**Comment by berndfinger** [comment]
Hi Michael,

I just checked and can confirm that:
- RHEL 8.2 comes with rhel-system-roles-sap version 2.0.0-1.el8_2
- RHEL 8.4 comes with rhel-system-roles-sap version 3.0.1-4.el8 (and 2.0.0-7.el8).
All are in repo rhel-8-for-$(uname -m)-sap-solutions-e4s-rpms.

A project is ongoing which will supports installing the latest version of RHEL System Roles for SAP from Automation Hub and from Galaxy.

Regards,
Bernd

**Comment by michaelk71** [comment]
Hello Bernd, 

just for info.
```
# dnf repoquery 'rhel-system-roles-sap'
Updating Subscription Management repositories.
Last metadata expiration check: 0:45:41 ago on Tue 25 May 2021 02:37:32 AM EDT.
rhel-system-roles-sap-0:1.1-1.el8.noarch
rhel-system-roles-sap-0:1.1.1-1.el8_1.noarch
```

I assume the reason for this is that we have a subscription for "RHEL for SAP Applications" and not for "RHEL for SAP Solutuions".

Regards
Michael
