### ISSUE TITLE
Merge into default branch

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-preconfigure#142]
Hi,
it seems the latest releases and edits go into a subbranch called bz1928398 instead of master. It seems you have forgot to update the default branch :) Same for https://github.com/linux-system-roles/sap-hana-preconfigure and https://github.com/linux-system-roles/sap-netweaver-preconfigure

Greetings
Klaas

**Comment by berndfinger** [comment]
I initially had planned to push the branch bz1891642 to master/main. But now I will use the latest branch, bz1928398, once the QA has finished.

**Comment by berndfinger** [comment]
Done.
