### ISSUE TITLE
Remove dependency on yum group performance

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-preconfigure#172]
Hi,
because of the log4j debacle we noticed log4j is installed on all our sap systems because group install of performance
(performance includes parfait which has a dependency to log4j).

https://github.com/linux-system-roles/sap-preconfigure/blob/master/vars/RedHat_7.yml#L22

I am not seeing parfait or log4j from the OS RPMs being used by SAP on our systems so I am guessing this is just installed because SAP was too lazy to properly list their dependencies.

Source of the group install requirement: https://launchpad.support.sap.com/#/notes/2002167

Maybe you could use your red hat contacts to get them to drop the requirement from their notes and/or at least remove performance from this role.

Greetings
Klaas

**Comment by Klaas-** [comment]
sap has confirmed that parfait is not used by SAP, not sure if they'll update the sap note any time soon though :)

**Comment by berndfinger** [comment]
Closing after copying over to https://github.com/sap-linuxlab/community.sap_install/issues/10
