### ISSUE TITLE
pam_limits should be strings, not ints

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-preconfigure#26]
currently running sap-preconfigure produces messages like:
 [WARNING]: The value 32800 (type int) in a string field was converted to u'32800' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

pam_limits expects a string not an int so all the values have to be quoted.

https://github.com/idiv-biodiversity/ansible/blob/devel/lib/ansible/modules/system/pam_limits.py#L156

**Comment by berndfinger** [comment]
Many thanks! I had encountered this issue before but had no time to open an issue yet. I just merged your pull request.
