### ISSUE TITLE
uuidd status detection not reliable

### ISSUE THREAD

**Issue by berndfinger** [linux-system-roles/sap-preconfigure#37]
In case of the following:

- "systemctl status uuidd" reports:
uuidd.service - Daemon for generating UUIDs
   Loaded: loaded (/usr/lib/systemd/system/uuidd.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since XXX ago
  Process: YYY ExecStart=/usr/sbin/uuidd --socket-activation (code=exited, status=1/FAILURE)
 Main PID: YYY (code=exited, status=1/FAILURE)

- systemd reports in /var/log/messages:
XXX systemd[1]: uuidd.socket: Socket unit configuration has changed while unit has been running, no open socket file descriptor left. The socket unit is not functional until restarted.

, uuidd will have an ActiveState of "failed" but the systemd Ansible module does not fail. So the status checking for uuidd has to be changed.

Restarting uuidd.socket solves this problem.

**Comment by rhmk** [comment]
Maybe the ansible module service_facts is also helpful here. See example in firewalld bug.

**Comment by berndfinger** [comment]
I'll just make sure uuidd AND uuidd.socket will be enabled and active.

**Comment by berndfinger** [comment]
fixed by pull request #52
